### ISSUE TITLE
Some problem on chatEngine.User(uuid).get()

### ISSUE THREAD

**Issue by tribushevsky** [pubnub/chat-engine-apple#12]
I try to receive user via uuid and hatEngine.User(uuid).get(), but this method return nil for valid uuid.

I created a user named 'Vladimir' earlier. And after that I created user using CENUser *user = self.client.User(@"PubNub").create(); and had tried to receive user with uuid 'Vladimir'.

How can I get CENUser object using existing uuid for user which be created in past?

**Comment by parfeon** [comment]
This issue is the same as #5 and #11 where presence event don't fire (issue with presence events in channel groups which currently examined by engineers). `get` can be used only if local client _seen_ requested user - this can be watched by listening for `$.online.join` event:  

```objc
client.on(@"$.online.join", ^(CENChat *chat, CENUser *user) {
    // From this point 'user' can be fetched with 'get()' method.
});
```

Aside from update of users through presence events it is possible to create user as you did and it works. Here is example:  

```objc
self.client = [CENChatEngine clientWithConfiguration:configuration];
    
self.client.on(@"$.ready", ^(CENMe *me) {
    NSString *userID = [NSUUID UUID].UUIDString;
    self.client.User(userID).create();
        
    NSLog(@"Created user: %@", self.client.User(userID).get()); 
    // Created user: <CENUser:0x6080000c59b0 uuid: 'B9717796-7586-49BF-B689-F164E223AB56'; state set: NO>
});
self.client.connect(@"PubNub").perform();
```

**Comment by tribushevsky** [comment]
Ok, but if I use authKey for authentication? I need to implement auth logic inside functions in PubNub server, but when i will be create user using `self.client.User(userID).create();` this request return unauthorized response, cause there is no auth key and I don't know just key for this user.

**Comment by parfeon** [comment]
[wiki](https://github.com/pubnub/chat-engine-apple/wiki/reference-chatengine#parameters-3) page describes where `authKey` is used and has reference on [authentication concept](https://github.com/pubnub/chat-engine-apple/wiki/concepts-authentication) and there is nothing about own service or function for authorization. If it is required by your authentication logic, you can change it, but by default `authKey` acts as _password_ for user with _uuid_.

I've shared working example and didn't saw any `unauthorized response` errors.  
What exactly you tried to do, to make that error appear?

**Comment by tribushevsky** [comment]
In PubNub functions I created validator for user's uuid and auth_token. 
How it work: I pass a uuid and auth_token to PubNub functions when try to connect to user, call My server method (auth_token_for_uuid), receive auth token and if auth_token from my server and auth_token from mobile client is equal I allow to connect to chat.

It is my custom auth logic, which I implemented on PubNub functions.

**Comment by parfeon** [comment]
When ChatEngine instance create another user (which already has been created with another instance) using `self.client.User(userID).create()` - there shouldn't be any network calls here. 

So what exactly you try to do with non-local user which you created with `create()` method?
Why do you call PubNub function directly? It is intended to work as standalone solution (but sure it can hit some third-party services, but number of calls is limited) and called solely by ChatEngine clients which know when and how it should be called.

Also, is it possible to share code which you passed to `authPolicy`?

**Comment by parfeon** [comment]
`authPolicy` called each time, when remote user try to do something (join chat, leave or invite someone). Is something happens locally - it never reach ChatEngine Functions.
