### ISSUE TITLE
Property 'connect' not found on object of type 'CENChatEngine *'

### ISSUE THREAD

**Issue by tribushevsky** [pubnub/chat-engine-apple#14]
I need to use ChatEngineIOS in existing application. I tried to realize some functionality in other project and there all fine but on existing project I get an error ' Property 'connect' not found on object of type 'CENChatEngine *' for this code: `chatEngine.connect(uuid).state(@{@"Hello" : @"World"}).perform();`

My pod file: 

```
platform :ios, '9.0'

target "Hello" do
     pod 'CENChatEngine'
end
```

**Comment by parfeon** [comment]
Extension app - do you mean watchOS app?

**Comment by tribushevsky** [comment]
Existing. Sorry.

**Comment by parfeon** [comment]
Ahh, my bad. I headed what I wanted to see. Your question is correct. 

Just tried on another project to add new dependency against `CENChatEngine` and tested connection - no issues there.
Can you check, what value assigned to `CHATENGINE_USE_BUILDER_INTERFACE` in **Pod** project for `CENChatEngine` target _Build settings_? It should be **1**.

Another way to try, is to:
1. Quit Xcode
2. De-integrate pod: `pod deintegrate <project-file-name>.xcodeproj`
3. Remove `Derived Data`
4. `pod install`
5. Open created Xcode workspace file.

**Comment by tribushevsky** [comment]
![screen shot 2018-07-05 at 17 09 38](https://user-images.githubusercontent.com/26404633/42330708-64bced28-807c-11e8-8705-588fab02c818.png)

**Comment by parfeon** [comment]
It happens, because you didn’t import framework properly.
Check [here](https://github.com/pubnub/chat-engine-apple/wiki/get-started#pubnub-chatengine) to see what exactly is wrong.

**Comment by tribushevsky** [comment]
I am not use `use_framework!` in Podfile. So `#import "ChatEngine.h"` is valid.
I fixed this situation after adding `COCOAPODS=1` and `CHATENGINE_USE_BUILDER_INTERFACE=1` macros to Preprocessor Macros in `Project -> Build Settings -> Apple LLVM 9.0 - Preprocessing`
![screen shot 2018-07-05 at 18 53 38](https://user-images.githubusercontent.com/26404633/42333982-e2a6ff6e-8084-11e8-9c26-8c15bc5cb2f5.png)
.

**Comment by parfeon** [comment]
Those flags should be added automatically. There something wrong happened pens on `pod install` step.

**Comment by tribushevsky** [comment]
Thank you for help!
