### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by tribushevsky** [pubnub/chat-engine-apple#6]
Hello! What about the Push Notifications?
For this functionality should I use a PubNub API or a ChatEngine has an interfaces for that?

**Comment by parfeon** [comment]
Hi!

This was the only plugin for which documentation not released. But it has been fixed and now this [wiki](https://github.com/pubnub/chat-engine-apple/wiki/plugins-push-notifications) page contain information about plugin which should be used to enable push notifications for [Chat](https://github.com/pubnub/chat-engine-apple/wiki/reference-caht) and allow to pre-format published dictionary with keys which is common for platform on which notification should be shown.

**Comment by tribushevsky** [comment]
Thank you for answer!
