### ISSUE TITLE
How can I get chats for user?

### ISSUE THREAD

**Issue by tribushevsky** [pubnub/chat-engine-apple#7]
I need to receive all chats that user was be joined in past.
Is PubNub save any info about joining user to different chats or I need to realize it myself?

**Comment by parfeon** [comment]
You need to set [this](https://github.com/pubnub/chat-engine-apple/wiki/reference-configuration#synchronizesession) configuration option to **YES** during ChatEngine configuration.

Listen for `$.group.restored`:  
```objc
self.client.me.session.on(@"$.group.restored", ^(NSString *chatsGroup) {
    if ([chatsGroup isEqualToString:CENChatGroups.custom]) {
        NSLog(@"Local user chats: %@", self.client.me.session.chats[chatsGroup]);
    }
});
```

There is few chat groups, but all user-created chats will be stored in group represented by `CENChatGroups.custom`.

Also it is possible to track changes on list of chats (from another devices authorized for same user) by listening [`$.chat.join`](https://github.com/pubnub/chat-engine-apple/wiki/reference-session#event-chat-join) and [`$.chat.leave`](https://github.com/pubnub/chat-engine-apple/wiki/reference-session#event-chat-leave) events.

**Comment by tribushevsky** [comment]
I think that you made a mistake in this line:
`if ([chatsGroup isEqualToString:CENChatGroups.custom])`

Maybe do you mean this code?

```
chatEngine.me.session.on(@"$.group.restored", ^(NSString *chatsGroup) {
        if ([chatsGroup isEqualToString: CENChatGroup.custom]) {
            NSLog(@"Local user chats: %@", chatEngine.me.session.chats[chatsGroup]);
        }
    });
```

**Comment by parfeon** [comment]
Yep, it happens sometime to mess up with name of typedef itself. Sorry about that!

**Comment by tribushevsky** [comment]
I found that chatEngine.chats contain this chats after configuring client using `configuration.synchronizeSession = YES;`

**Comment by parfeon** [comment]
Indeed, but it require some time to fetch them. That is why I suggest also use emitted events to track down changes in list.
Also you requested list of chats, to which user joined. `chatEngine.chats` may also contain chats which has been created but not connected to (when any CENUser instance created, it also create two chat instances for `feed` and `direct`, but don't connect). So I suggest use information from `me.session.chats` as it is the only place where you will find list of chats to which user connected.
