### ISSUE TITLE
How to receive all users that was be connected to chat?

### ISSUE THREAD

**Issue by tribushevsky** [pubnub/chat-engine-apple#8]
I need to receive all users, that was be connected to appropriate chat.

Imagine the situation. I create a user with uuid 'HelloWorld' after that I create a chat with name 'HelloWorld'. After that I close the app and create a new user with uuid 'SomeNewUser' on my second phone. For user with uuid 'SomeNewUser' I create a chat with name 'HelloWorld' and I need to receive all users (in that case 'HelloWorld' and 'SomeNewUser'). 

How can I do it using ChatEngine API?
Is PubNub save any info about joining users to chat with particular uuid or I need to realize it myself?

**Comment by parfeon** [comment]
There is no join history in ChatEngine and I don't remember such functionality in PubNub SDK as well.
